---

- name: "nginx:enable:vhost | Links the vhost configuration into <sites-enabled> directory "
  file:
    state: link
    dest:  "{{ item.from }}"
    src:   "{{ item.to }}"
  with_items:
    - '{ "to": "{{ nginx_path_sites_available ~ "/" ~ nginx_vhost_name }}", "from": "{{ nginx_path_sites_enabled ~ "/" ~ nginx_vhost_name }}" }'
  notify:  'service:nginx:reload'