---

- debug: var=passed_vars
  tags: nginx

- include: "nginx/install/repository.yml"
  tags:    [nginx, install, repository]

- include: "nginx/install/package.yml"
  tags:    [nginx, install, repository]

- include: "nginx/get/service/status.yml"
  tags:    [nginx, get, service, status]

- include: "nginx/create/sites-available/directory.yml"
  tags:    [nginx, create, sites-available, directory]

- include: "nginx/create/sites-enabled/directory.yml"
  tags:    [nginx, create, sites-enabled, directory]

- include: "nginx/create/log/directory.yml"
  tags:    [nginx, create, log, directory]

- include: "nginx/disable/default/vhost.yml"
  tags:    [nginx, disable, default, vhost]

- include: "nginx/remove/default/vhost.yml"
  tags:    [nginx, disable, default, vhost]

- include: "nginx/service/start.yml"
  when:    '( (not nginx_service_is_running|bool) and (nginx_start_service == true) )'
  tags:    [nginx, service, start]

# @TODO currently not working. Need a way to access tags of command invocation - 'tags' variable holds the ones defined on the task itself.
#- include: "nginx/service/stop.yml"
#  when:    '( ("nginx" in tags) and ("service" in tags) and ("stop" in tags) )'
#  tags:    [nginx, service, stop]

- include: "nginx/service/reload.yml"
  when:    '( nginx_service_is_running|bool )'
  tags:    [nginx, service, reload]



