---

##
## @param nginx_path_ssl_certs
##
- name: "nginx:create:ssl-certs:directory | Create directory for enabled vhosts "
  file:
    state: 'directory'
    path:  '{{ item.path }}'
  with_items:
    - '{{ nginx_path_ssl_certs }}'