---

- name: "service:nginx:start"
  service:
    name:  'nginx'
    state: 'started'

- name: "service:nginx:reload"
  service:
    name:  'nginx'
    state: 'reloaded'

- name: "service:nginx:restart"
  service:
    name:  'nginx'
    state: 'restarted'

- name: "service:nginx:stop"
  service:
    name:  'nginx'
    state: 'started'

