---

- name: "nginx:create:vhosts | Create configured vhosts "
  template:
    src:  '../../../templates/nginx/nginx-vhost.conf.j2'
    dest: '{{ nginx_path_sites_available }}'
  with_items:
    - '{ "vhost": "{{ nginx_vhost_name }}" }'
  notify:
    - 'service:nginx:reload'
