---

##
## @param nginx_path_sites_enabled
##
- name: "nginx:create:sites-enabled:directory | Create directory for enabled vhosts "
  file:
    state: 'directory'
    path:  '{{ item.path }}'
  with_items:
    - '{ "path": "{{ nginx_path_sites_enabled }}" }'