---

##
## @param nginx_path_sites_http_auth
##
- name: "nginx:create:http-auth:directory | Create directory for http authentication files "
  file:
    state: 'directory'
    path:  '{{ item.path }}'
  with_items:
    - '{{ nginx_path_sites_http_auth }}'
  sudo:    true